<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.v3" Version="2.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="!Exists('$(MSBuildProjectDirectory)/.mockbuilder/build/output/ExtremeRoles.dll')">
    <PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.8.18" PrivateAssets="all" />
    <ProjectReference Include="..\ExtremeRoles\ExtremeRoles.csproj" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(NuGetPackageRoot)amongus.gamelibs.steam/2026.8.18/ref/net6.0/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(NuGetPackageRoot)amongus.gamelibs.steam/2026.8.18/ref/net6.0/Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(NuGetPackageRoot)amongus.gamelibs.steam/2026.8.18/ref/net6.0/Il2CppSystem.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/.mockbuilder/build/output/ExtremeRoles.dll')">
    <Reference Include="$(MSBuildProjectDirectory)/.mockbuilder/build/output/*.dll" />
  </ItemGroup>

</Project>