using System;

using System.Text;
using System.Text.RegularExpressions;

using ExcelDataReader;

using Microsoft.CodeAnalysis;

namespace ExtremeRoles.Generator;

[Generator]
public sealed class TranslationGenerator : ISourceGenerator
{
	public void Execute(GeneratorExecutionContext context)
	{
		// Build up the source code
		string source = $@"// <auto-generated/>
using System;
using ExtremeRoles.Helper;

namespace ExtremeRoles
{{
    public static class Test
    {{
        static void HelloFrom(string name) =>
            Logging.Debug($""Generator says: Hi from '{{name}}'"");
    }}
}}
";
		
		// Add the source code to the compilation
		context.AddSource("test.g.cs", source);
	}

	public void Initialize(GeneratorInitializationContext context)
	{

	}
}
