name: AutoBuildAndTransCheck


on: 
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build_check:
    runs-on: windows-latest
    if: contains(github.event.pull_request.labels.*.name, 'ReadyToMerge')
    steps:
      - name: Generate token
        id: gen_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v1
      - name: RestoreNugetPackage
        run: nuget restore ExtremeRoles.sln
      - name: SetupPython
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: InstallPythonLibrary
        run: pip install -r requirements.txt
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v1.1
      - name: RunBuild
        id: build
        continue-on-error: true
        run: msbuild ExtremeRoles.sln -t:restore,build -p:Configuration=Release -p:RestorePackagesConfig=true
      - name: CheckTransData
        continue-on-error: true
        run: python createtransdatareport.py ${{ steps.build.outcome }}
      - name: PostComment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
            GITHUB_TOKEN: ${{ steps.gen_token.outputs.token }}
            pr_number: ${{ github.event.number }}
            filePath: .github/workflows/comment.md
