name: AutoBuildAndTransCheck


on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build_check:
    runs-on: windows-2025
    if: contains(github.event.pull_request.labels.*.name, 'ReadyToMerge')
    steps:
      - name: Generate token
        id: gen_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v4
      - name: RestoreNugetPackage
        run: nuget restore ExtremeRoles.sln
      - name: SetupPython
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
      - name: InstallPythonLibrary
        run: pip install -r requirements.txt
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v3
      - name: RunTests
        env:
          TestableAmongUsAccess: ${{ secrets.TESTABLEAMONGUSACCESS }}
        run: powershell ./run_coverage.ps1
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Generate Coverage Report
        run: reportgenerator -reports:"**/*.cobertura.xml;**/coverage.cobertura.xml;**/*.xml;**/*.cov" -targetdir:"CoverageReport" -reporttypes:Html
      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: CoverageReport
      - name: RunBuild
        id: build
        run: msbuild ExtremeRoles.sln -t:restore,build -p:Configuration=Release -p:RestorePackagesConfig=true
      - name: CheckTransData
        if: always() && steps.build.outcome != 'skipped'
        run: python createtransdatareport.py ${{ steps.build.outcome }}
      - name: PostComment
        if: always() && steps.build.outcome != 'skipped'
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ steps.gen_token.outputs.token }}
          issue-number: ${{ github.event.number }}
          body-path: .github/workflows/comment.md
